### ISSUE TITLE
Plugins non-compatible with V1.5.2

### ISSUE THREAD

**Issue by bigalgeorge** [dignajar/bludit-documentation#51]
Hi there I looked, saw and was impressed by the code footprint and flexibility of Bludit.
Installed and then tried to insert an image without documentation. Standard editor for image insert gives a prompt; not really wysiwyg. But never mind ckeditor will fix:Addons/Ckeditor installed, non compatible would not upload image. Next, my favourite Trubowyg editor installed, non compatible and visually not work (controls not visible).

Sorry but until Bludit can at least do the basics with easy image manipulation, it is not ready for general use. But my goodness, it does look very close to perfect.

Please tell me I am wrong and point out my errors in above comments. Id like to do a review of Bludit as if this can be fixed, it is surely a very good option for CMS.

**Comment by clickwork-git** [comment]
Shure can Bludit do basics. There are two things concerning the new backend that will be fixed in the next version.

1) As stated several times before here at GitHub, in the forum and in Gitter, the notification "incompatible with" does not mean incompatible (see https://github.com/dignajar/bludit/issues/360).

2) Uploading images is easy and works fine. Click "General" on the right side of the editor field, than "Images". This feature should not to be "hidden".

**Comment by bigalgeorge** [comment]
Hi there. Thanks for rapid reply. Unfortunately theres no chat here, but there is no "General" on left side of standard editor is that what you mean?

**Comment by bigalgeorge** [comment]
Hi I see "General" on right side of Trumbowyg presume thats what you mean. See what Trumbo looks here Ive attached.
![selection_008](https://cloud.githubusercontent.com/assets/6935387/20846649/878a03c4-b92f-11e6-8d83-e4ab9fe27d23.png)

**Comment by clickwork-git** [comment]
There is a chat at

https://gitter.im/dignajar/bludit

I will have a look at Trumbowyg. It seems that the author does no longer update his plugins. :-(

**Comment by bigalgeorge** [comment]
Got it - pays to read documention - like you said but its on the RIGHT side of page of standard editor.
Thanks. will chat. More to follow for others reading this...................

**Comment by clickwork-git** [comment]
Sorry... reft and light. Now edited.

**Comment by Torsten-K** [comment]
This is surely the user friendliest way. Alternatively, you can upload images into the directory _bl-content/uploads/img_ via FTP, for example if you want to prepare pictures for later use. Then, after logging in into your Bludit installation, in the editor you can include one of those pictures using the Markdown syntax, like so: `![short description](img/my-picture.jpg)`. Bludit finds the picture, so there is no need to type in the whole path.

I always find it nice to have several options.

**Comment by dignajar** [comment]
Please use the Bludit repository no the documentation repository. thanks
