### ISSUE TITLE
Feature request: Individual meta title

### ISSUE THREAD

**Issue by Torsten-K** [dignajar/bludit-documentation#53]
When typing in a title for a page, this title is used for the navigation menu item, which makes sense so far. And it is also automatically used for the meta title in the HTML head, and the site name is added (like: My new page – My wonderful website). But it would be better if users could type in a custom meta title, individually for every page, for SEO reasons. I imagine this could be done similar to the text field for the meta description (right beside the SimpleMDE Markdown Editor). But as I am no programmer, I cannot do this by myself and would be happy if this would be a new feature in a future release.

**Comment by dignajar** [comment]
Hi, this kind of request makes it on Bludit repository, not here in the documentation.
Thanks
